#!/bin/bash

# Read 'SCRIPT_VERSION' string from target script
# and provide to Major, Minor and Patch version number
#
# Version string example:
#
# SCRIPT_VERSION=0.1.2
#
# Parameters:
#
# $1 - Script to parse
# $2 - Version type to return ('major', 'minor' or 'patch')

set -e

SCRIPT="${1}"
VERSION_TYPE="${2}"

script_version=$(cat "${SCRIPT}" | grep "SCRIPT_VERSION=" | sed "s/SCRIPT_VERSION=//g")

if [ "${VERSION_TYPE}" = "" ]; then
    echo "${script_version}"
    exit 0
fi

if [ "${VERSION_TYPE}" = "major" ]; then
    echo $(echo ${script_version} | sed 's/\./ /g' | gawk '{ print $1 }')
    exit 0
fi

if [ "${VERSION_TYPE}" = "minor" ]; then
    echo $(echo ${script_version} | sed 's/\./ /g' | gawk '{ print $2 }')
    exit 0
fi

if [ "${VERSION_TYPE}" = "patch" ]; then
    echo $(echo ${script_version} | sed 's/\./ /g' | gawk '{ print $3 }')
    exit 0
fi
